name: ðŸ”¥ Fix images ðŸ”¥

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Fix private key
        run: echo "${{ secrets.FIREBASE_PRIVATE_KEY }}" > private-key.txt
      - name: Install Dependencies
        working-directory: backend
        run: npm install
      - name: Run Fix Images
        working-directory: backend
        run: |
          export FIREBASE_PRIVATE_KEY=$(cat ../private-key.txt)
          cd try && node fixnews.js
        env:
            FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
            FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
            FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
            FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
            FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
            GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
            NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
            R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
            R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}